-- Delete all data from all tables
DELETE FROM FIND.SEARCH_INDEXES;
DELETE FROM FIND.SEARCH_PARAMETRIC_VALUES;
DELETE FROM FIND.SEARCH_STORED_STATE;
DELETE FROM FIND.SEARCH_CONCEPT_CLUSTER_PHRASES;
DELETE FROM FIND.SEARCHES;
DELETE FROM FIND.USERS;
